export {
  ATTRIBUTES,
  CLASSES,
  RACES,
  SPELLS,
  INVENTORY_ITEMS,
  WITCHER_HOMELANDS as HOMELANDS,
  WITCHER_SCHOOLS_LIST,
  WITCHER_BACKGROUNDS as WITCHER_LIFEPATH_PROMPTS,
  WITCHER_SIMPLE_CRITICAL_TABLE,
  WITCHER_HIT_LOCATION_TABLE,
  getModifier,
  formatModifier,
  rollDice,
  parseDiceNotation,
  rollDiceFormula,
  calculateHP,
  calculateStamina,
  calculateResolve,
  calculateFocus,
  calculateVigor,
  calculateRun,
  calculateLeap,
  calculateEncumbrance,
  calculateRecovery,
  calculateWoundThreshold,
  calculateStun,
  calculateDefense,
  calculateInitiative,
  calculateAttributeBudget,
  xpForLevel,
  createRandomWitcherAttributes,
  createRandomWitcherBackground,
  getHitLocation,
  getSimpleCritical,
  getRaceByValue,
  getProfessionByValue,
  RARITY_COLORS,
} from "@/features/witcher-system/rules/core";

export type {
  AttributeKey,
  CharacterClass,
  CharacterRace,
} from "@/features/witcher-system/rules/core";
