import {
  ATTRIBUTES,
  CLASSES,
  HOMELANDS,
  RACES,
  WITCHER_SCHOOLS_LIST,
} from "@/lib/rpg-utils";
import type {
  CharacterSheetDraft,
  SheetDefinition,
  SheetScalarValue,
} from "@/lib/sheets/types";

export const NOIR_CHRONICLE_SHEET: SheetDefinition = {
  id: "witcher-trpg-core",
  slug: "witcher-trpg-sheet",
  version: 2,
  sections: [
    { id: "identity", label: "Identidade", kind: "identity" },
    { id: "resources", label: "Recursos", kind: "resources" },
    { id: "combat", label: "Combate", kind: "combat" },
    { id: "attributes", label: "Atributos", kind: "attributes" },
    { id: "narrative", label: "Narrativa", kind: "narrative" },
    { id: "attachments", label: "Vinculos", kind: "attachments" },
  ],
  fields: [
    {
      id: "name",
      label: "Nome do personagem",
      binding: "name",
      type: "text",
      sectionId: "identity",
      stepId: "identity",
      required: true,
      defaultValue: "",
    },
    {
      id: "homeland",
      label: "Terra natal",
      binding: "homeland",
      type: "select",
      sectionId: "identity",
      stepId: "identity",
      defaultValue: "Temeria",
      options: HOMELANDS.map((value) => ({ label: value, value })),
    },
    {
      id: "appearance",
      label: "Aparencia",
      binding: "appearance",
      type: "textarea",
      sectionId: "narrative",
      stepId: "identity",
      defaultValue: "",
    },
    {
      id: "race",
      label: "Raca",
      binding: "race",
      type: "select",
      sectionId: "identity",
      stepId: "race",
      defaultValue: "humano",
      options: RACES.map((race) => ({ label: race.label, value: race.value })),
    },
    {
      id: "class",
      label: "Profissao",
      binding: "class",
      type: "select",
      sectionId: "identity",
      stepId: "class",
      defaultValue: "witcher",
      options: CLASSES.map((profession) => ({
        label: profession.label,
        value: profession.value,
      })),
    },
    {
      id: "school",
      label: "Escola",
      binding: "school",
      type: "select",
      sectionId: "identity",
      stepId: "class",
      defaultValue: "Lobo",
      options: WITCHER_SCHOOLS_LIST.map((value) => ({ label: value, value })),
    },
    ...ATTRIBUTES.map((attribute) => ({
      id: attribute.key,
      label: attribute.label,
      binding: attribute.key,
      type: "number" as const,
      sectionId: "attributes",
      stepId: "attributes",
      min: 2,
      max: 10,
      defaultValue: 5,
      helpText: attribute.description,
    })),
    {
      id: "background",
      label: "Historico",
      binding: "background",
      type: "textarea",
      sectionId: "narrative",
      stepId: "history",
      defaultValue: "",
    },
    {
      id: "lifepath",
      label: "Caminho de vida",
      binding: "lifepath",
      type: "textarea",
      sectionId: "narrative",
      stepId: "history",
      defaultValue: "",
    },
    {
      id: "level",
      label: "Nivel",
      binding: "level",
      type: "number",
      sectionId: "resources",
      defaultValue: 1,
      min: 1,
      max: 10,
    },
    {
      id: "experience",
      label: "Experiencia",
      binding: "experience",
      type: "number",
      sectionId: "resources",
      defaultValue: 0,
      min: 0,
    },
    {
      id: "gold",
      label: "Coroas",
      binding: "gold",
      type: "number",
      sectionId: "resources",
      defaultValue: 120,
      min: 0,
    },
    {
      id: "speed",
      label: "Movimento",
      binding: "speed",
      type: "number",
      sectionId: "combat",
      defaultValue: 18,
      min: 0,
    },
  ],
  wizardSteps: [
    { id: "identity", label: "Identidade", fieldBindings: ["name", "homeland", "appearance"] },
    { id: "race", label: "Raca", fieldBindings: ["race"] },
    { id: "class", label: "Profissao", fieldBindings: ["class", "school"] },
    {
      id: "attributes",
      label: "Atributos",
      fieldBindings: ATTRIBUTES.map((attribute) => attribute.key),
    },
    { id: "history", label: "Caminho", fieldBindings: ["background", "lifepath"] },
  ],
  derivedFields: [
    { id: "hp-max", label: "Vida maxima", binding: "hp_max", dependencies: ["body"], compute: "hp" },
    { id: "hp-current", label: "Vida atual", binding: "hp_current", dependencies: ["hp_max"], compute: "hp" },
    { id: "sta-max", label: "Estamina maxima", binding: "sta_max", dependencies: ["body"], compute: "sta" },
    { id: "sta-current", label: "Estamina atual", binding: "sta_current", dependencies: ["sta_max"], compute: "sta" },
    { id: "resolve-max", label: "Determinacao", binding: "resolve_max", dependencies: ["will", "int"], compute: "resolve" },
    { id: "resolve-current", label: "Determinacao atual", binding: "resolve_current", dependencies: ["resolve_max"], compute: "resolve" },
    { id: "focus-max", label: "Foco", binding: "focus_max", dependencies: ["will", "int"], compute: "focus" },
    { id: "focus-current", label: "Foco atual", binding: "focus_current", dependencies: ["focus_max"], compute: "focus" },
    { id: "vigor-max", label: "Vigor", binding: "vigor_max", dependencies: ["class"], compute: "vigor" },
    { id: "vigor-current", label: "Vigor atual", binding: "vigor_current", dependencies: ["vigor_max"], compute: "vigor" },
    { id: "armor-class", label: "Defesa", binding: "armor_class", dependencies: ["ref", "dex"], compute: "defense" },
    { id: "initiative-bonus", label: "Iniciativa", binding: "initiative_bonus", dependencies: ["ref"], compute: "initiative" },
    { id: "run", label: "Corrida", binding: "run", dependencies: ["spd"], compute: "run" },
    { id: "leap", label: "Salto", binding: "leap", dependencies: ["spd"], compute: "leap" },
    { id: "enc", label: "Fardo", binding: "enc", dependencies: ["body"], compute: "enc" },
    { id: "rec", label: "Recuperacao", binding: "rec", dependencies: ["body", "will"], compute: "rec" },
    { id: "wound-threshold", label: "Limiar de ferimento", binding: "wound_threshold", dependencies: ["body", "will"], compute: "wound-threshold" },
    { id: "stun", label: "Atordoamento", binding: "stun", dependencies: ["body", "will"], compute: "stun" },
    { id: "xp-next", label: "XP para o proximo nivel", binding: "xp_next", dependencies: ["level"], compute: "xp-next" },
    { id: "point-budget", label: "Pontos investidos", binding: "point_budget_used", dependencies: ATTRIBUTES.map((attribute) => attribute.key), compute: "point-budget" },
    ...ATTRIBUTES.map((attribute) => ({
      id: `modifier-${attribute.key}`,
      label: `Modificador de ${attribute.label}`,
      binding: `modifier.${attribute.key}`,
      dependencies: [attribute.key],
      compute: "attribute-modifier" as const,
      attributeKey: attribute.key,
    })),
  ],
  repeatingGroups: [
    { id: "inventory", label: "Inventario", binding: "inventory", itemType: "inventory" },
    { id: "spellbook", label: "Magias", binding: "spellbook", itemType: "spellbook" },
  ],
  validationRules: [
    {
      id: "identity-name-required",
      scope: "field",
      target: "name",
      message: "Nome do personagem e obrigatorio.",
    },
    {
      id: "attributes-point-budget",
      scope: "step",
      target: "attributes",
      message: "Os atributos iniciais nao podem passar de 60 pontos.",
    },
  ],
  formulaDeps: [
    { binding: "hp_max", dependsOn: ["body"] },
    { binding: "sta_max", dependsOn: ["body"] },
    { binding: "resolve_max", dependsOn: ["will", "int"] },
    { binding: "focus_max", dependsOn: ["will", "int"] },
    { binding: "vigor_max", dependsOn: ["class"] },
    { binding: "armor_class", dependsOn: ["ref", "dex"] },
    { binding: "initiative_bonus", dependsOn: ["ref"] },
    { binding: "xp_next", dependsOn: ["level"] },
    { binding: "point_budget_used", dependsOn: ATTRIBUTES.map((attribute) => attribute.key) },
  ],
  presentationHints: [
    { binding: "hp_max", surface: "metric", emphasis: "strong", icon: "heart" },
    { binding: "sta_max", surface: "metric", emphasis: "strong", icon: "zap" },
    { binding: "focus_max", surface: "metric", emphasis: "default", icon: "sparkles" },
    { binding: "resolve_max", surface: "metric", emphasis: "default", icon: "shield" },
    { binding: "inventory", surface: "panel", emphasis: "default", icon: "package" },
    { binding: "spellbook", surface: "panel", emphasis: "default", icon: "book-open-text" },
  ],
  bindings: {
    inventory: "inventory",
    spellbook: "spellbook",
  },
};

export const NOIR_CHRONICLE_DEFAULTS: CharacterSheetDraft = {
  name: "",
  race: "humano",
  class: "witcher",
  level: 1,
  experience: 0,
  gold: 120,
  speed: 18,
  homeland: "Temeria",
  school: "Lobo",
  background: "",
  lifepath: "",
  appearance: "",
  attributes: Object.fromEntries(ATTRIBUTES.map((attribute) => [attribute.key, 5])),
};

export function createNoirChronicleInitialValues(): Record<string, SheetScalarValue> {
  const values: Record<string, SheetScalarValue> = {};

  for (const field of NOIR_CHRONICLE_SHEET.fields) {
    values[field.binding] = field.defaultValue ?? null;
  }

  return values;
}
